<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Craft update at any time.
 *
 * If you want to change any of these settings, copy it into craft/config/db.php, and make your change there.
 */

$url=parse_url(getenv(“CLEARDB_DATABASE_URL”));
	return array(
	‘server’ => $url[“host”],
	‘user’ => 'b9b435def22196',
	‘password’ => '6474105d',
	‘database’ => 'heroku_52495e0f62a7de3',
	‘tablePrefix’ => ‘craft’,
	);
