<?php

/**
 * DO NOT EDIT THIS FILE.
 *
 * This file is subject to be overwritten by a Craft update at any time.
 *
 * If you want to change any of these settings, copy it into craft/config/db.php, and make your change there.
 */
/** mysql://b9b435def22196:6474105d@us-cdbr-iron-east-03.cleardb.net/heroku_52495e0f62a7de3?reconnect=true */
$url = parse_url(getenv("CLEARDB_DATABASE_URL"));
$host = $url["host"];
$username = $url["user"];
$password = $url["pass"];
$database = substr($url["path"], 1);
$connection = new mysqli($server, $username, $password, $db);
